"""adding phoneno column to users

Revision ID: 7670701a586a
Revises: b3d3dc078c9d
Create Date: 2022-02-11 11:54:31.892643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7670701a586a'
down_revision = 'b3d3dc078c9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phoneno', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phoneno')
    # ### end Alembic commands ###
